server:
  port: 8081

spring:
    datasource:
        url: jdbc:h2:~/imed;DB_CLOSE_ON_EXIT=FALSE
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create-drop
        show-sql: true
    sql: 
        init:
            mode: always
    h2:
        console:
            enabled: true
    # security:
    #     user:
    #         name: admin
    #         password: admin
    #     oauth2:
    #         resourceserver:
    #             jwt:
    #                 issuer-uri: http://localhost:8080/auth/realms/imed
    #                 jwk-set-uri: http://localhost:8080/auth/realms/imed/protocol/openid-connect/certs